# Generated by Django 6.0 on 2025-12-26 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuel',
            options={'verbose_name': 'Пальне', 'verbose_name_plural': 'Пальне'},
        ),
        migrations.AlterModelOptions(
            name='pump',
            options={'verbose_name': 'Колонка', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакція', 'verbose_name_plural': 'Транзакції'},
        ),
        migrations.AlterField(
            model_name='fuel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Залишок'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='core.fuel', verbose_name='Тип пального'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва/Номер'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Вільна'), ('BUSY', 'Зайнята'), ('OUT_OF_ORDER', 'Не працює')], default='AVAILABLE', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fuel', verbose_name='Пальне'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='liters',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Літри'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pump', verbose_name='Колонка'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
