# Generated by Django 6.0 on 2025-12-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fuel_options_alter_pump_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='color_code',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Колір (HEX)'),
        ),
    ]
